# Generated by Django 2.0.7 on 2020-02-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200207_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteuser',
            name='fullname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inviteuser',
            name='invite_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], max_length=20, null=True),
        ),
    ]
