# Generated by Django 2.0.7 on 2020-02-10 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200210_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
