# Generated by Django 2.0.7 on 2020-02-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='secret_code',
            field=models.IntegerField(max_length=6),
        ),
    ]
