# Generated by Django 2.0.7 on 2020-02-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200217_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='secret_code',
            field=models.IntegerField(),
        ),
    ]
