# Generated by Django 2.0.7 on 2020-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200217_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=20),
        ),
    ]
