# Generated by Django 2.0.7 on 2020-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_phoneverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
