# Generated by Django 2.0.7 on 2020-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200408_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CELEBRITY_ENQUIRY', 'CELEBRITY_ENQUIRY'), ('SERVICE_ENQUIRY', 'SERVICE_ENQUIRY'), ('CART_SHARE', 'CART_SHARE')], max_length=30, null=True),
        ),
    ]
