# Generated by Django 2.0.7 on 2020-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200415_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
