# Generated by Django 2.0.7 on 2020-04-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200424_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
