# Generated by Django 2.0.7 on 2020-05-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200429_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart_url',
            field=models.URLField(null=True),
        ),
    ]
