# Generated by Django 3.1.1 on 2023-03-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_cart_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CELEBRITY_ENQUIRY', 'CELEBRITY_ENQUIRY'), ('SERVICE_APPROVAL', 'SERVICE_APPROVAL'), ('SERVICE_ENQUIRY', 'SERVICE_ENQUIRY'), ('CART_SHARE', 'CART_SHARE')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.state'),
        ),
    ]
