# Generated by Django 3.1.1 on 2023-03-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20230301_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
