# Generated by Django 3.1.1 on 2023-03-14 05:19

from django.db import migrations


def migrate_to_user_model(apps, schema_editor):
    User = apps.get_model('users', 'CustomUser')
    for user_obj in User.objects.all():
        user_obj.cart_url = None
        user_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_address_state'),
    ]

    operations = [
        migrations.RunPython(migrate_to_user_model)
    ]
