# Generated by Django 3.1.1 on 2023-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20230314_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CELEBRITY_ENQUIRY', 'CELEBRITY_ENQUIRY'), ('SERVICE_APPROVAL', 'SERVICE_APPROVAL'), ('SERVICE_REJECTED', 'SERVICE_REJECTED'), ('SERVICE_ENQUIRY', 'SERVICE_ENQUIRY'), ('CART_SHARE', 'CART_SHARE')], max_length=30, null=True),
        ),
    ]
