# Generated by Django 3.1.1 on 2024-02-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customuser_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
