# Generated by Django 3.1.1 on 2024-06-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20240201_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CELEBRITY_ENQUIRY', 'CELEBRITY_ENQUIRY'), ('SERVICE_APPROVAL', 'SERVICE_APPROVAL'), ('SERVICE_REJECTED', 'SERVICE_REJECTED'), ('SERVICE_ENQUIRY', 'SERVICE_ENQUIRY'), ('SERVICE_SUSPENDED', 'SERVICE_SUSPENDED'), ('CART_SHARE', 'CART_SHARE')], max_length=30, null=True),
        ),
    ]
