# Generated by Django 3.2 on 2024-06-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20240606_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_cart_url_updated',
            field=models.BooleanField(default=False),
        ),
    ]
