# Generated by Django 3.2 on 2024-07-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_customuser_is_cart_url_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
