# Generated by Django 3.2 on 2024-07-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_city_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
