# Generated by Django 3.1.1 on 2024-07-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20240724_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalMesssage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('img_url', models.URLField(blank=True, null=True)),
                ('userType', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('USER', 'User'), ('VENDOR', 'Vendor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
