# Generated by Django 3.1.1 on 2024-10-07 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20240730_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRolesMaster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('role_desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.adminrolesmaster')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
