# Generated by Django 3.1.1 on 2024-10-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_adminroles_adminrolesmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CELEBRITY_ENQUIRY', 'CELEBRITY_ENQUIRY'), ('SERVICE_APPROVAL', 'SERVICE_APPROVAL'), ('SERVICE_REJECTED', 'SERVICE_REJECTED'), ('SERVICE_ENQUIRY', 'SERVICE_ENQUIRY'), ('SERVICE_SUSPENDED', 'SERVICE_SUSPENDED'), ('CART_SHARE', 'CART_SHARE'), ('ARTICLE_PUBLISHED', 'ARTICLE_PUBLISHED'), ('CELEBRITY_ADDED', 'CELEBRITY_ADDED'), ('VENDOR_ADDED', 'VENDOR_ADDED'), ('NEW_PROMOTION', 'NEW_PROMOTION'), ('SERVICE_LIKED', 'SERVICE_LIKED'), ('SERVICE_FAV', 'SERVICE_FAV')], max_length=30, null=True),
        ),
    ]
