# Generated by Django 3.1.1 on 2024-11-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20241010_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='params',
            field=models.TextField(blank=True, null=True),
        ),
    ]
